---
title: "Figure3_clean_plots"
author: "CEB"
date: '2024-12-06'
output: html_document
---

##load packages
```{r}
library(tidyverse)

#for bayesian analysis:
library(brms)
library(tidybayes)

#for interpreting interactions:
library(emmeans)

#for plots:
library(ggnewscale)
library(RColorBrewer)


#for combining plot:
library(cowplot)
```




###----ROOT LENGTH~PRODUCTIVITY MODEL - NO OUTLIER, TETIAROA ONLY--------
```{r}
##load data-----
#load data-
root_dat<-read.csv("../data/RootData4Casey_241125.csv")

#add region column:-
root_dat<-
  root_dat%>%
  mutate(Region = case_when(grepl("SEY", Plot)~ "Seychelles",
                             TRUE~ "Tetiaroa"))%>%
  relocate(Region, .before = Motu)
root_dat

##remove outlier-----
root_dat_no_out<-
  root_dat%>%
  filter(!(Motu == "Iti"&RootCore == 1))

###restrict to Tetiaroa-------
root_dat_no_out_Tet<-
root_dat_no_out%>%
  filter(Region == "Tetiaroa")

##center variables-----------
root_dat_no_out_Tet_c<-
  root_dat_no_out_Tet%>%
   mutate(NPP_MJ_m2_year_c = base::scale(NPP_MJ_m2_year, center = TRUE, scale = FALSE))

root_length_prod_linear_Tetiaroa_no_c<-readRDS("brms/root_length_prod_linear_Tetiaroa_no_c.RDS") 


```


#create nice plot for fig3 to coombine with marine data:
```{r}

me_npp_bio_lin_Tet<-conditional_effects(root_length_prod_linear_Tetiaroa_no_c, prob = .75, effects = 'NPP_MJ_m2_year_c', plot = FALSE)[[1]]

mean(root_dat_no_out_Tet$NPP_MJ_m2_year) #8.273426

#unscale:----
me_npp_bio_lin_Tet_unscale<-
  me_npp_bio_lin_Tet%>%
    mutate(NPP_MJ_m2_year = NPP_MJ_m2_year_c+8.273426)



root_length_prod_plot<-
root_dat_no_out_Tet %>%
  ggplot(aes(x = NPP_MJ_m2_year, y = Length_Km_m2)) +
    geom_point(pch = 21, size = 2, colour = "#33A02C", fill = "#33A02C", alpha = .8) + #, size = .8
    geom_line(data = me_npp_bio_lin_Tet_unscale, aes(x = NPP_MJ_m2_year, y = estimate__), lwd = 1.2, colour = "#33A02C") +
        geom_ribbon(data = me_npp_bio_lin_Tet_unscale, aes(x = NPP_MJ_m2_year, y = estimate__, ymin = lower__, ymax=upper__), alpha = .2, fill = "#33A02C")+
    #ylab(expression(atop("Ground-dwelling arthropod", paste(energy~requirements~(log~kj~day^-1)))))+  
 ylab(expression(atop("Fine root length", paste((km~m^-2)))))+
    xlab(expression(Fine~root~productivity~(MJ~m^-2~yr^-1)))+
  theme_bw()+
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
            text = element_text(size = 14),
        legend.position=c(.8, .2),
        legend.box = "horizontal",
        legend.title = element_text(hjust = .5),
        legend.box.background = element_rect()
    )

root_length_prod_plot

```


######-------MARINE DATA FOR FIG 3-------------

#load data
```{r}
#coral data
coral_met_function_dat<-read.csv("../data/Fig3a_coral_transect.csv")

#parrotfish/urchin data
herb_met_function_dat<-read.csv("../data/Fig3b_parrot_transect_v3.csv")
#update october 15 - now has tetiaroa data in it 

#site data (to get region and atoll)
site_dat<-read.csv("../data/Energetics_sites_Oct.csv")
site_dat
```

#combine data
```{r}
site_dat2<-
  site_dat%>%
  mutate(Site.Name = Marine.Site.Names)


coral_met_function_dat_site<-
  right_join(select(site_dat2, c(Region, Atoll, Island, Site.Name, Rats)), coral_met_function_dat, by = "Site.Name")

coral_met_function_dat_site
#n = 24 transects

herb_met_function_dat_site<-
  right_join(select(site_dat2, c(Region, Atoll, Island, Site.Name, Rats)), herb_met_function_dat, by = "Site.Name")

herb_met_function_dat_site
#n = 146 transects, INCLUDING SHALLOW SEYCHELLES SITES AND FREGATE H & M SEPERATE***

herb_met_function_dat_site_noSS<-
  herb_met_function_dat_site%>%
  filter(Location!="shallow")
herb_met_function_dat_site_noSS
#now n = 134 transects

herb_met_function_dat_site_noSS%>%
  group_by(Site.Name)%>%
  summarize(n_trans = length(Transect))
#n = 34 sites

herb_met_function_dat_site_noSS_FrHM<-
  herb_met_function_dat_site_noSS%>%
  mutate(Site.Name2 = if_else(Site.Name == "Fregate H"|Site.Name=="Fregate M", "Fregate H-M", Site.Name))%>%
  relocate(Site.Name2, .after = Site.Name)%>%
  filter(Island  != "Tiaraunu") #remove Tiaraunu because only 2 transects
herb_met_function_dat_site_noSS_FrHM
#now n  = 132 transects

herb_met_function_dat_site_noSS_FrHM%>%
  group_by(Site.Name2)%>%
  summarize(n_trans = length(Transect))
#n = 32 sites


##add in new group-level effects-----
herb_met_function_dat_site_noSS_FrHM<-
  herb_met_function_dat_site_noSS_FrHM%>%
  mutate(Atoll_or_Island = case_when(Region == "Seychelles" ~ Island,
                                     Region == "Tetiaroa" ~ Region,
                                     Region == "Chagos" ~ Atoll))%>%
  relocate(Atoll_or_Island, .after = Atoll)
herb_met_function_dat_site_noSS_FrHM


```


###parrotfish data for plots-----
```{r}

herb_met_function_dat_site_noSS_FrHM_wTia<-
  herb_met_function_dat_site_noSS%>%
  mutate(Site.Name2 = if_else(Site.Name == "Fregate H"|Site.Name=="Fregate M", "Fregate H-M", Site.Name))%>%
  relocate(Site.Name2, .after = Site.Name)
herb_met_function_dat_site_noSS_FrHM_wTia
#now n  = 134 transects

##add in new group-level effects-----
herb_met_function_dat_site_noSS_FrHM_wTia<-
  herb_met_function_dat_site_noSS_FrHM_wTia%>%
  mutate(Atoll_or_Island = case_when(Region == "Seychelles" ~ Island,
                                     Region == "Tetiaroa" ~ Region,
                                     Region == "Chagos" ~ Atoll))%>%
  relocate(Atoll_or_Island, .after = Atoll)
herb_met_function_dat_site_noSS_FrHM_wTia

#center and scale:-----
herb_met_function_dat_site_noSS_FrHM_wTia<-
  herb_met_function_dat_site_noSS_FrHM_wTia%>%
  mutate(parrot_energy_MJ_m2_yr_cs = base::scale(parrot_energy_MJ_m2_yr, center = TRUE, scale = TRUE),
         parrot_energy_MJ_m2_yr_c = base::scale(parrot_energy_MJ_m2_yr, center = TRUE, scale = FALSE))


herb_met_function_dat_site_noSS_FrHM_wTia2<-
  herb_met_function_dat_site_noSS_FrHM_wTia%>%
  mutate(log_parrot_energy = log(parrot_energy_MJ_m2_yr+1),
         log_parrot_energy_c = base::scale(log_parrot_energy, center = TRUE, scale = FALSE),
         log_parrot_sediment = log(parrot_sediment_kg_m2_yr+1))


###LOAD MODEL-----
parrot_met_func_mod_group_c_FrHM2_log_log_v3_wTia<-readRDS("brms/parrot_met_func_mod_group_c_FrHM2_log_log_v3_wTia.RDS") 


```


###extract effects and plot from final parrotfish models------
```{r}

hypothesis(parrot_met_func_mod_group_c_FrHM2_log_log_v3_wTia, "log_parrot_energy_c>0") #1	*


###extract outputs log model--------
#extract effects----
parrot_met_func_mod_group_c_FrHM2_log_log_v3_wTia %>%
  spread_draws(b_log_parrot_energy_c) %>%
  median_hdi(b_log_parrot_energy_c)
#effect         lower        upper   width  point  interval
#1.329715	      1.169449	1.482861	.95     median    hpdi


parrot_met_func_mod_group_c_FrHM2_log_log_v3_wTia %>%
  spread_draws(b_log_parrot_energy_c) %>%
  median_hdi(2^b_log_parrot_energy_c)
#2.51353	2.249258	2.795025	

#because both x and y log-transformed, now: 
#for each doubling in parrotfish energy requirements (mj/m2/year), parrotfish sediment production increases by a factor of 2.51 (95% HPDI = 2.25 to 2.80) 


#log-log model plots-----
#effect line:
me_herb2_log<-conditional_effects(parrot_met_func_mod_group_c_FrHM2_log_log_v3_wTia, prob = .75, effects = 'log_parrot_energy_c', plot = FALSE)[[1]]

mean(herb_met_function_dat_site_noSS_FrHM_wTia2$log_parrot_energy) #0.3821432

me_herb2_log_uncenter<-
  me_herb2_log%>%
  mutate(herbenergy_unscale = log_parrot_energy_c+0.3821432)

parrot_energy_sed_plot<-
herb_met_function_dat_site_noSS_FrHM_wTia2 %>%
  ggplot(aes(x = log_parrot_energy, y = log_parrot_sediment)) +
        geom_point(pch = 21, size = 2, colour = "#1F78B4", fill = "#1F78B4", alpha = .8) + #, size = .8
    geom_line(data = me_herb2_log_uncenter, aes(x = herbenergy_unscale, y = estimate__), lwd = 1.2, colour = "#1F78B4") +
        geom_ribbon(data = me_herb2_log_uncenter, aes(x = herbenergy_unscale, y = estimate__, ymin = lower__, ymax=upper__), alpha = .2, fill = "#1F78B4")+
  theme_bw()+
    xlab(expression(Parrotfish~energy~requirements~(log~MJ~m^-2~year^-1)))+
   # ylab(expression(Parrotfish~sediment~production~(log~kg~m^-2~year^-1)))+  
     ylab(expression(atop("Parrotfish sediment production", paste((log~kg~m^-2~year^-1)))))+
  theme_bw()+
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
            text = element_text(size = 14),
        legend.position=c(.8, .2),
        legend.box = "horizontal",
        legend.title = element_text(hjust = .5),
        legend.box.background = element_rect()
    )
parrot_energy_sed_plot

##make both log-scale axes labels:------
parrot_energy_sed_plot_log_axis<-
herb_met_function_dat_site_noSS_FrHM_wTia2 %>%
  ggplot(aes(x = log_parrot_energy, y = log_parrot_sediment)) +
        geom_point(pch = 21, size = 2, colour = "#1F78B4", fill = "#1F78B4", alpha = .8) + #, size = .8
    geom_line(data = me_herb2_log_uncenter, aes(x = herbenergy_unscale, y = estimate__), lwd = 1.2, colour = "#1F78B4") +
        geom_ribbon(data = me_herb2_log_uncenter, aes(x = herbenergy_unscale, y = estimate__, ymin = lower__, ymax=upper__), alpha = .2, fill = "#1F78B4")+
  theme_bw()+
    xlab(expression(Parrotfish~energy~flow~(MJ~m^-2~yr^-1)))+
   # ylab(expression(Parrotfish~sediment~production~(log~kg~m^-2~year^-1)))+  
     ylab(expression(atop("Parrotfish sediment production", paste((kg~m^-2~yr^-1)))))+
       scale_y_continuous(labels = c(0, 1,  5, 10, 20), breaks = c(log(1), log(2),  log(6), log(11), log(21)))+ #because of +1 in log-transformation, here log(1) = 0*** and subtract 1 from all labels
       scale_x_continuous(labels = c(0, 1, 2, 4, 6), breaks = c(log(1), log(2), log(3), log(5), log(7)))+ #because of +1 in log-transformation, here log(1) = 0*** and subtract 1 from all labels
  theme_bw()+
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
            text = element_text(size = 14),
        legend.position=c(.8, .2),
        legend.box = "horizontal",
        legend.title = element_text(hjust = .5),
        legend.box.background = element_rect()
    )
parrot_energy_sed_plot_log_axis
```



####---CORALS----------
```{r}
#try centering predictor----
coral_met_function_dat_site_cs<-
    coral_met_function_dat_site%>%
  mutate(coral_net_PP_MJ_m2_yr_cs = base::scale(coral_net_PP_MJ_m2_yr, center = TRUE, scale = TRUE),
         coral_net_PP_MJ_m2_yr_c = base::scale(coral_net_PP_MJ_m2_yr, center = TRUE, scale = FALSE))
coral_met_function_dat_site_cs


##load final coral  model:---
coral_met_func_mod_group_c<-readRDS("brms/coral_met_func_mod_group_c.RDS") 


```


#Coral models - plots
```{r}

#effect line:
me_coral<-conditional_effects(coral_met_func_mod_group_c, prob = .75, effects = 'coral_net_PP_MJ_m2_yr_c', plot = FALSE)[[1]]
mean(coral_met_function_dat_site_cs$coral_net_PP_MJ_m2_yr) #2.626238

me_coral_uncenter<-
  me_coral%>%
  mutate(coral_pp_unscale = coral_net_PP_MJ_m2_yr_c+2.626238)

coral_energy_prod_plot<-
coral_met_function_dat_site_cs %>%
  ggplot(aes(x = coral_net_PP_MJ_m2_yr, y = coral_G_kg_m2_yr)) +
    geom_point(pch = 21, size = 2, colour = "#FCBBA1", fill = "#FCBBA1", alpha = .8) + #, size = .8
    geom_line(data = me_coral_uncenter, aes(x = coral_pp_unscale, y = estimate__), lwd = 1.2, colour = "#FCBBA1") +
        geom_ribbon(data = me_coral_uncenter, aes(x = coral_pp_unscale, ymin = lower__, ymax=upper__), alpha = .2, fill = "#FCBBA1")+
  theme_bw()+
    xlab(expression(Coral~productivity~(MJ~m^-2~yr^-1)))+
 #   ylab(expression(Coral~carbonate~production~(kg~m^-2~year^-1)))+  
   ylab(expression(atop("Coral carbonate production", paste((kg~m^-2~yr^-1)))))+
  scale_x_continuous(breaks = c(0, 2, 4, 6, 8), labels = c(0, 2, 4, 6, 8))+
  theme_bw()+
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
            text = element_text(size = 14),
        legend.position=c(.8, .2),
        legend.box = "horizontal",
        legend.title = element_text(hjust = .5),
        legend.box.background = element_rect()
    )
coral_energy_prod_plot

```


###COMBINE FIG 3
```{r}
coral_energy_prod_plot
parrot_energy_sed_plot_log_axis
root_length_prod_plot

#horizontal:
Fig3<-plot_grid(root_length_prod_plot, coral_energy_prod_plot, parrot_energy_sed_plot_log_axis, labels = "auto", label_fontface = "bold", nrow = 1)
Fig3

##vertical:
Fig3_vert<-plot_grid(root_length_prod_plot, coral_energy_prod_plot, parrot_energy_sed_plot_log_axis, labels = "auto", label_fontface = "bold", ncol = 1)
Fig3_vert

```



###COMBINE FIG 3 AND SAVE - FOR A4
```{r}

#coral plots, made it a shade darker:
coral_energy_prod_plota4<-
coral_met_function_dat_site_cs %>%
  ggplot(aes(x = coral_net_PP_MJ_m2_yr, y = coral_G_kg_m2_yr)) +
    geom_point(pch = 21, size = 2, colour = "#fba988", fill = "#fba988", alpha = .8) + #, size = .8 #FCBBA1
    geom_line(data = me_coral_uncenter, aes(x = coral_pp_unscale, y = estimate__), lwd = 1.2, colour = "#fba988") +
        geom_ribbon(data = me_coral_uncenter, aes(x = coral_pp_unscale, ymin = lower__, ymax=upper__), alpha = .2, fill = "#FCBBA1")+
  theme_bw()+
    xlab(expression(Coral~productivity~(MJ~m^-2~yr^-1)))+
    ylab(expression(Coral~carbonate~production~(kg~m^-2~yr^-1)))+  
  # ylab(expression(atop("Coral carbonate production", paste((kg~m^-2~yr^-1)))))+
  scale_x_continuous(breaks = c(0, 2, 4, 6, 8), labels = c(0, 2, 4, 6, 8))+
  theme_bw()+
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
            text = element_text(size = 9.5),
        legend.position=c(.8, .2),
        legend.box = "horizontal",
        legend.title = element_text(hjust = .5),
        legend.box.background = element_rect()
    )
coral_energy_prod_plota4


parrot_energy_sed_plot_log_axisa4<-
herb_met_function_dat_site_noSS_FrHM_wTia2 %>%
  ggplot(aes(x = log_parrot_energy, y = log_parrot_sediment)) +
        geom_point(pch = 21, size = 2, colour = "#1F78B4", fill = "#1F78B4", alpha = .8) + #, size = .8
    geom_line(data = me_herb2_log_uncenter, aes(x = herbenergy_unscale, y = estimate__), lwd = 1.2, colour = "#1F78B4") +
        geom_ribbon(data = me_herb2_log_uncenter, aes(x = herbenergy_unscale, y = estimate__, ymin = lower__, ymax=upper__), alpha = .2, fill = "#1F78B4")+
  theme_bw()+
    xlab(expression(Parrotfish~energy~flow~(MJ~m^-2~yr^-1)))+
   ylab(expression(Parrotfish~sediment~production~(kg~m^-2~yr^-1)))+  
    # ylab(expression(atop("Parrotfish sediment production", paste((kg~m^-2~yr^-1)))))+
       scale_y_continuous(labels = c(0, 1,  5, 10, 20), breaks = c(log(1), log(2),  log(6), log(11), log(21)))+ #because of +1 in log-transformation, here log(1) = 0*** and subtract 1 from all labels
       scale_x_continuous(labels = c(0, 1, 2, 4, 6), breaks = c(log(1), log(2), log(3), log(5), log(7)))+ #because of +1 in log-transformation, here log(1) = 0*** and subtract 1 from all labels
  theme_bw()+
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
            text = element_text(size = 9.5),
        legend.position=c(.8, .2),
        legend.box = "horizontal",
        legend.title = element_text(hjust = .5),
        legend.box.background = element_rect()
    )
parrot_energy_sed_plot_log_axisa4


root_length_prod_plota4<-
root_dat_no_out_Tet %>%
  ggplot(aes(x = NPP_MJ_m2_year, y = Length_Km_m2)) +
    geom_point(pch = 21, size = 2, colour = "#33A02C", fill = "#33A02C", alpha = .8) + #, size = .8
    geom_line(data = me_npp_bio_lin_Tet_unscale, aes(x = NPP_MJ_m2_year, y = estimate__), lwd = 1.2, colour = "#33A02C") +
        geom_ribbon(data = me_npp_bio_lin_Tet_unscale, aes(x = NPP_MJ_m2_year, y = estimate__, ymin = lower__, ymax=upper__), alpha = .2, fill = "#33A02C")+
    #ylab(expression(atop("Ground-dwelling arthropod", paste(energy~requirements~(log~kj~day^-1)))))+  
# ylab(expression(atop("Fine root length", paste((km~m^-2)))))+
   ylab(expression(Fine~root~length~(km~m^-2)))+
    xlab(expression(Fine~root~productivity~(MJ~m^-2~yr^-1)))+
  theme_bw()+
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
            text = element_text(size = 9.5),
        legend.position=c(.8, .2),
        legend.box = "horizontal",
        legend.title = element_text(hjust = .5),
        legend.box.background = element_rect()
    )

root_length_prod_plota4

##combine and save----

Fig3<-plot_grid(coral_energy_prod_plota4, parrot_energy_sed_plot_log_axisa4, root_length_prod_plota4, labels = "auto", label_fontface = "bold", nrow = 1,  label_size = 12, hjust = c(0, .75, -2.5), vjust = 1)
Fig3

#ggsave(Fig3, filename = "../figures/Fig3_A4.jpg", width = 8.2, height = 3)

##vertical:
Fig3_vert<-plot_grid(coral_energy_prod_plota4, parrot_energy_sed_plot_log_axisa4, root_length_prod_plota4, labels = "auto", label_fontface = "bold", ncol = 1,  label_size = 12)
Fig3_vert

#ggsave(Fig3_vert, filename = "../figures/Fig3_A4_vert.jpg", width = 3.5, height = 8)

```