---
title: "supplement_seabird_to_processes"
author: "CEB"
date: '2026-02-13'
output: html_document
---

#load packages
```{r}
library(tidyverse)

#for bayesian analysis:
library(brms)
library(tidybayes)

#for extracting effects:
library(emmeans)

#scientific notation funny in some of csvs, fix:
options(scipen=999)

#for plotting
library(RColorBrewer)
library(ggnewscale)

#for combining plot:
library(cowplot)

```

####-----MARINE ANALYSIS--------

#load data
```{r}
#coral data
coral_met_function_dat<-read.csv("../data/Fig3a_coral_transect.csv")

#parrotfish data
herb_met_function_dat<-read.csv("../data/Fig3b_parrot_transect_v3.csv")

#site data (to get region and atoll)
site_dat<-read.csv("../data/Energetics_sites_Oct.csv")
site_dat

#seabirds data:
sb_dat_by_isl<-read.csv("../data/Fig1_seabirds_by_island.csv") #this is summed per island


```


#combine data
```{r}
site_dat2<-
  site_dat%>%
  mutate(Site.Name = Marine.Site.Names)


coral_met_dat_site<-
  right_join(select(site_dat2, c(Region, Atoll, Island, Site.Name, Rats)), coral_met_function_dat, by = "Site.Name")

coral_met_dat_site
#n = 24 transects

coral_met_dat_site_seabird<-
    left_join(coral_met_dat_site, sb_dat_by_isl, by = "Island")
coral_met_dat_site_seabird



herb_met_function_dat_site<-
  right_join(select(site_dat2, c(Region, Atoll, Island, Site.Name, Rats)), herb_met_function_dat, by = "Site.Name")

herb_met_function_dat_site
#n = 146 transects, need to exclude shallow seychelles transects, combine fregate H & M

herb_met_function_dat_site_noSS<-
  herb_met_function_dat_site%>%
  filter(Location!="shallow")
herb_met_function_dat_site_noSS
#now n = 134 transects

herb_met_function_dat_site_noSS%>%
  group_by(Site.Name)%>%
  summarize(n_trans = length(Transect))
#n = 34 sites

herb_met_function_dat_site_noSS_FrHM_wTia<-
  herb_met_function_dat_site_noSS%>%
  mutate(Site.Name2 = if_else(Site.Name == "Fregate H"|Site.Name=="Fregate M", "Fregate H-M", Site.Name))%>%
  relocate(Site.Name2, .after = Site.Name)
herb_met_function_dat_site_noSS_FrHM_wTia
#n  = 134 transects

herb_met_function_dat_site_noSS_FrHM_wTia%>%
  group_by(Site.Name)%>%
  summarize(n_trans = length(Transect))
#n = 34 sites

herb_met_function_dat_site_noSS_FrHM_wTia%>%
  group_by(Island)%>%
  summarize(n_trans = length(Transect))
#n = 27 islands - good all matches other file

##add in new group-level effects-----
herb_met_function_dat_site_noSS_FrHM_wTia<-
  herb_met_function_dat_site_noSS_FrHM_wTia%>%
  mutate(Atoll_or_Island = case_when(Region == "Seychelles" ~ Island,
                                     Region == "Tetiaroa" ~ Region,
                                     Region == "Chagos" ~ Atoll))%>%
  relocate(Atoll_or_Island, .after = Atoll)
herb_met_function_dat_site_noSS_FrHM_wTia


#combine with seabirds: 
herb_met_function_dat_site_seabird<-
    left_join(herb_met_function_dat_site_noSS_FrHM_wTia, sb_dat_by_isl, by = "Island")
herb_met_function_dat_site_seabird

```



##parrotfish models
```{r}
range(herb_met_function_dat_site_seabird_cs$parrot_sediment_kg_m2_yr)
###run model------
herb_met_function_dat_site_seabird_cs<-
  herb_met_function_dat_site_seabird%>%
    ungroup()%>%
  mutate(log_parrot_sed = log(parrot_sediment_kg_m2_yr+1), 
         Ninput_kgha_log = log(Ninput_kgha+1),
         Ninput_kgha_c = base::scale(Ninput_kgha, center = TRUE, scale = FALSE),
          Ninput_kgha_log_c = base::scale(Ninput_kgha_log, center = TRUE, scale = FALSE))
herb_met_function_dat_site_seabird_cs


parrot_sediment_n_input_mod_group_log_log<-
  brm(
 log_parrot_sed~Ninput_kgha_log_c + (1|Region) + (1|Region:Atoll_or_Island),
  data = herb_met_function_dat_site_seabird_cs, 
  iter = 3000, warmup = 1000, chains = 4, cores = 4,
   control = list(adapt_delta = 0.999, max_treedepth = 15), 
      file = "brms/parrot_sediment_n_input_mod_group_log_log")  
print(parrot_sediment_n_input_mod_group_log_log) #0 divergent trans
pp_check(parrot_sediment_n_input_mod_group_log_log) #looks okay, tried other distributions but doesn't make much difference
plot(parrot_sediment_n_input_mod_group_log_log)

hypothesis(parrot_sediment_n_input_mod_group_log_log, "Ninput_kgha_log_c>0") #PP = .96***

###results identical regardless of distributions used. use the same as in main text. 

```



###corals: seabirds vs. carbonate production-----
```{r}
coral_met_dat_site_seabird

#try centering and scaling predictor, can log response because G is positive (unlike net PP)---
range(coral_met_dat_site_seabird$coral_G_kg_m2_yr)

coral_met_dat_site_seabirdcs<-
    coral_met_dat_site_seabird%>%
  ungroup()%>%
  mutate(
         Ninput_kgha_cs = base::scale(Ninput_kgha, center = TRUE, scale = TRUE),
         Ninput_kgha_c = base::scale(Ninput_kgha, center = TRUE, scale = FALSE),
         log_Ninput_kgha = log(Ninput_kgha),
         log_Ninput_kgha_c = base::scale(log_Ninput_kgha, center = TRUE, scale = FALSE),
         log_coral_G = log(coral_G_kg_m2_yr)
)
coral_met_dat_site_seabirdcs


##add in group-level effects - Chagos only data so only need atoll----
#best with log(n input)-----
coral_G_sb_mod_group_log<-
  brm(
 coral_G_kg_m2_yr~log_Ninput_kgha_c + (1|Atoll),
  data = coral_met_dat_site_seabirdcs, 
  iter = 3000, warmup = 1000, chains = 4, cores = 4,
   control = list(adapt_delta = 0.999, max_treedepth = 15), 
      file = "brms/coral_G_sb_mod_group_log") 
#worked!

print(coral_G_sb_mod_group_log)
pp_check(coral_G_sb_mod_group_log) #looks good
plot(coral_G_sb_mod_group_log) #looks good
hypothesis(coral_G_sb_mod_group_log, "log_Ninput_kgha_c>0") #0.99*** still very strong 


###results identical regardless of distributions used. very strong link from seabird N input to coral carbonate production - use the same as in main text. 


```

####---------TERRESTRIAL ANALYSIS------------

#load terrestrial data
```{r}
#data from eleanor:
root_dat<-read.csv("../data/RootData4Casey_021225.csv") #3.96 scaling factor for mg C to mj
root_dat


#add region column:
root_dat<-
  root_dat%>%
  mutate(Region = case_when(grepl("SEY", Plot)~ "Seychelles",
                             TRUE~ "Tetiaroa"))%>%
  relocate(Region, .before = Motu)
root_dat

#split data, center data (use only tetiaroa, as per explanations in other files)----
#Eleanor said likely something wrong with one core's biomass measurement - so remove (hit a coral or something):----
root_dat_no_out<-
  root_dat%>%
    filter(Region == "Tetiaroa")%>%
  filter(!(Motu == "Iti"&RootCore == 1))%>%
  mutate(native_perc_c = base::scale(NativeForestFraction, center = TRUE, scale = FALSE),
         rootn15_c = base::scale(RootsN15, center = TRUE, scale = FALSE),
         soiln15_c = base::scale(SoilN15, center = TRUE, scale = FALSE))

```


### Analysis: - fine root length vs. seabirds and native forest*
```{r}

#response = Length_Km_m2 (log to match main text and see how that looks)
range(root_dat_no_out$Length_Km_m2)

##tetiaroa only (use soil n15 to match lizards/arthropods)----
tet_root_length_log<-
  brm(
 log(Length_Km_m2) ~ native_perc_c * soiln15_c + (1|Motu), 
  data = root_dat_no_out, 
  iter = 3000, warmup = 1000, chains = 4, cores = 4,
   control = list(adapt_delta = 0.999, max_treedepth = 15), 
      file = "brms/tet_root_length_log") #worked fine

print(tet_root_length_log)
pp_check(tet_root_length_log) #looks pretty good
plot(tet_root_length_log, ask = FALSE)

hypothesis(tet_root_length_log, c("native_perc_c>0", # .86
                                        "soiln15_c>0", #.25
                                        "native_perc_c:soiln15_c>0")) #.76
#so weaker effects than with PP, but trending the same

```


###------------ALL PLOTS FOR SUPPLEMENT-------------

##Root length plot---------
```{r}
##extract effects:
me_npp_int_log_tet_soil_rl<-conditional_effects(tet_root_length_log, prob = .75, 'native_perc_c:soiln15_c', plot = FALSE)[[1]]
emmip(tet_root_length_log, soiln15_c~native_perc_c , cov.reduce = range)
# For numeric variables, mean + (-1:1) * SD are used as conditions.

mean(root_dat_no_out$SoilN15)#13.75579
mean(root_dat_no_out$NativeForestFraction)#76.2754


##new labels:
me_npp_int_log_tet_soil_rl_unscale2<-
  me_npp_int_log_tet_soil_rl%>%
  mutate(SoilN15 = soiln15_c + 13.75579,
         NativeForestFraction =native_perc_c +76.2754, 
         Soil_fact = as.factor(round(SoilN15, 0)))%>%
  mutate(Soil_fact = fct_recode(Soil_fact, low = "10", mid = "14", high = "17"))%>% #updated to 10 compared to full dataset*
  mutate(Soil_fact = fct_relevel(Soil_fact, "high", "mid", "low"))


root_length_vs_forest_soiln15_plot_log_axis<-
root_dat_no_out %>%
  ggplot(aes(x = NativeForestFraction, y = log(Length_Km_m2))) +
     geom_ribbon(data = me_npp_int_log_tet_soil_rl_unscale2, aes(x = NativeForestFraction, y = estimate__, ymin = lower__, ymax = upper__, fill = Soil_fact), lwd = 0, alpha = .2) +
geom_line(data = me_npp_int_log_tet_soil_rl_unscale2, aes(x = NativeForestFraction, y = estimate__, colour = Soil_fact), lwd = 1.2) +
    scale_colour_brewer(direction = -1, name = "", palette = "Greens")+#"YlOrRd"
  scale_fill_brewer(direction = -1,  name = "", palette = "Greens")+#"YlOrRd"
    new_scale_fill()+
       geom_point(aes(fill =  SoilN15), pch = 21, size = 2, alpha = .9) + #, size = .8 as.factor(Birds)
       scale_fill_distiller(direction = 1,  palette = "Greens" )+ #"YlOrRd"
    xlab("Native forest %")+
    ylab(expression(Fine~root~length~(km~m^-2)))+
 #scale_y_continuous(labels = c(exp(0),exp(1),exp(2),exp(3),exp(4)), breaks = c(0,1,2,3,4))+
   scale_y_continuous(labels = c(1, 2.5, 5, 10, 20, 50), breaks = c(log(1),log(2.5), log(5),log(10), log(20), log(50)))+
  #   scale_y_continuous(labels = c(0,1, 2.5, 5, 10, 20, 50), breaks = c(0,log(1),log(2.5), log(5),log(10), log(20), log(50)))+
  labs(fill = expression(Soil~delta^15~N))+
  theme_bw()+
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
              text = element_text(size = 14),
        legend.position=c(.2, .8),
        legend.box = "horizontal",
        legend.title = element_text(hjust = .5),
        legend.box.background = element_rect()
    )
root_length_vs_forest_soiln15_plot_log_axis



###resize plot and darken:----
#extract the 3 colors and manually darken them:
library(colorspace)   # for lighten() and darken()
pal <- brewer.pal(3, "Greens")
# Create darker line colors
line_cols  <- darken(pal, amount = 0.25)
# Create lighter ribbon colors
ribbon_cols <- darken(pal, amount = 0.25)

#also manually darken fill scale for points to match lines:
greens_base <- brewer.pal(9, "Greens")
greens_dark <- darken(greens_base, amount = 0.25)
greens_dark_continuous <- colorRampPalette(greens_dark)


me_npp_int_log_tet_soil_rl_unscale3<-
  me_npp_int_log_tet_soil_rl_unscale2%>%
  mutate(Soil_fact = fct_relevel(Soil_fact, "low", "mid", "high"))




root_length_vs_forest_soiln15_plot_log_axisa4<-
root_dat_no_out %>%
  ggplot(aes(x = NativeForestFraction, y = log(Length_Km_m2))) +
     geom_ribbon(data = me_npp_int_log_tet_soil_rl_unscale3, aes(x = NativeForestFraction, y = estimate__, ymin = lower__, ymax = upper__, fill = Soil_fact), lwd = 0, alpha = .2) +
geom_line(data = me_npp_int_log_tet_soil_rl_unscale3, aes(x = NativeForestFraction, y = estimate__, colour = Soil_fact), lwd = 1.2) + #
   # scale_colour_brewer(direction = 1, palette = "Greens", name ="")+#"YlOrRd"
 # scale_fill_brewer(direction = 1,  palette = "Greens", name = "")+#"YlOrRd"
  #replace with manually darkened colors:
     scale_colour_manual(values = line_cols, name ="")+
  scale_fill_manual(values = ribbon_cols, name = "")+
  #and also make different linetype to help distinguish:
#  scale_linetype_manual( values = c( high = "solid", mid  = "longdash", low  = "dashed"),  name = "")+
        guides(color = guide_legend(direction = "horizontal",  barwidth = .8,  #1.5 
    barheight = .1, override.aes = list(lwd = .4), order = 0)) +
    new_scale_fill()+
       geom_point(aes(fill =  SoilN15), pch = 21, size = 2, alpha = .9) +
     #  scale_fill_distiller(direction = 1,  palette = "Greens")+ 
  #replace with manually darkened scale:
         scale_fill_gradientn(colours = greens_dark_continuous(200))+ 
      guides(fill = guide_colorbar(direction = "horizontal",  barwidth = 6,   
    barheight = .2, order = 1, title.position = "top" )) +
      labs(fill = expression(Soil~delta^15~N))+
    xlab("Native vegetation cover (%)")+
    ylab(expression(Fine~root~length~(km~m^-2)))+
   scale_y_continuous(labels = c(1, 2.5, 5, 10, 20, 40), breaks = c(log(1),log(2.5), log(5),log(10), log(20), log(40)))+
  theme_bw()+
      theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
             text = element_text(size = 10),
        legend.position=c(.35, .9),
        legend.box = "vertical",
        legend.direction="horizontal",
               legend.key.width=unit(0.5,"cm"),
        legend.key.spacing.y = unit(-6, "pt"),
      #   legend.key.spacing.x = unit(-6, "pt"),
        legend.spacing = unit(-6, "pt"),
       legend.text = element_text(size = 6, margin = margin(l=0, b = 0)),
      legend.title = element_text(size = 6), #, margin = margin(b=.5)
      legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt"),
        legend.background = element_blank(),
         #legend.box.background = element_rect(),
      legend.box.background = element_blank())
root_length_vs_forest_soiln15_plot_log_axisa4

```




#Parrotfish sediment plots-------
```{r}

#log-log plot------
#effect line:
me_parrot_sed_sb_loglog<-conditional_effects(parrot_sediment_n_input_mod_group_log_log, prob = .75, effects = 'Ninput_kgha_log_c', plot = FALSE)[[1]]

mean(herb_met_function_dat_site_seabird_cs$Ninput_kgha_log) #2.296604

me_parrot_sed_sb_loglog_unscale<-
  me_parrot_sed_sb_loglog%>%
    mutate(Ninput_kgha_log = Ninput_kgha_log_c + 2.296604)


#log-log plot, but changed axes to be on log scale:
parrotfish_sed_sb_plot<-
herb_met_function_dat_site_seabird_cs %>%
  ggplot(aes(x = Ninput_kgha_log, y = log_parrot_sed)) +
     geom_point(pch = 21, size = 2, colour = "#1F78B4", fill = "#1F78B4", alpha = .8) + #, size = .8
    geom_line(data = me_parrot_sed_sb_loglog_unscale, aes(y = estimate__), lwd = 1.2, colour = "#1F78B4") +
        geom_ribbon(data = me_parrot_sed_sb_loglog_unscale, aes(y = estimate__, ymin = lower__, ymax=upper__), alpha = .2, fill = "#1F78B4")+
  ylab(expression(Parrotfish~sediment~production~(kg~m^-2~yr^-1)))+
       scale_y_continuous(labels = c(0, 1,  5, 10, 20), breaks = c(log(1), log(2),  log(6), log(11), log(21)))+ #because of +1 in log-transformation, here log(1) = 0*** and subtract 1 from all labels
 # scale_y_continuous(labels = c(exp(0),exp(1),exp(2),exp(3),exp(4)), breaks = c(0,1,2,3,4))+
   # ylab(expression(atop("Parrotfish energy", paste(requirements~(log~MJ~m^-2~year^-1)))))+  
    xlab(expression(Seabird~N~input~(kg~ha^-1~yr^-1)))+
       scale_x_continuous(labels = c(0,  10, 100, 400), breaks = c(log(1), log(11), log(101), log(401)))+
  theme_bw()+
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
             text = element_text(size = 14),
        legend.position='none')

parrotfish_sed_sb_plot


###clean up plot-----
parrotfish_sed_sb_plota4<-
herb_met_function_dat_site_seabird_cs %>%
  ggplot(aes(x = Ninput_kgha_log, y = log_parrot_sed)) +
     geom_point(pch = 21, size = 2, colour = "#1F78B4", fill = "#1F78B4", alpha = .8) + #, size = .8
    geom_line(data = me_parrot_sed_sb_loglog_unscale, aes(y = estimate__), lwd = 1.2, colour = "#1F78B4") +
        geom_ribbon(data = me_parrot_sed_sb_loglog_unscale, aes(y = estimate__, ymin = lower__, ymax=upper__), alpha = .2, fill = "#1F78B4")+
  ylab(expression(Parrotfish~sediment~production~(kg~m^-2~yr^-1)))+
       scale_y_continuous(labels = c(1, 2.5,  5, 10, 15), breaks = c(log(2), log(3.5), log(6), log(11), log(16)))+ #because of +1 in log-transformation, here log(1) = 0*** and subtract 1 from all labels
    xlab(expression(Seabird~N~input~(kg~ha^-1~yr^-1)))+
       scale_x_continuous(labels = c(0,  10, 100, 400), breaks = c(log(1), log(11), log(101), log(401)))+
  theme_bw()+
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
             text = element_text(size = 10),
        legend.position='none')

parrotfish_sed_sb_plota4


```



####Coral production plots-----
```{r}

##plot by atoll-----

#first get overall effect line:
me_coral_G_sb_pp_log<-conditional_effects(coral_G_sb_mod_group_log, prob = .75, effects = 'log_Ninput_kgha_c', plot = FALSE)[[1]]
mean(coral_met_dat_site_seabirdcs$log_Ninput_kgha) #0.1950983

me_coral_G_sb_pp_loguncenter<-
  me_coral_G_sb_pp_log%>%
  mutate(ninput_unscale = log_Ninput_kgha_c+0.1950983)

#now get atoll-specific lines:
me_coral_G_sb_pp_log_atoll<-conditional_effects(coral_G_sb_mod_group_log, prob = .75, effects = 'log_Ninput_kgha_c', re_formula=NULL, 
                    conditions = make_conditions(coral_met_dat_site_seabirdcs, vars = c("Atoll")), plot = FALSE)[[1]]

me_coral_G_sb_pp_log_atollluncenter<-
  me_coral_G_sb_pp_log_atoll%>%
  mutate(ninput_unscale = log_Ninput_kgha_c+0.1950983)


##truncated lines for each atoll-----
coral_met_dat_site_seabirdcs %>%
   filter(Atoll == "Great Chagos Bank")%>%
  summarize(range(log_Ninput_kgha)) #-3.101003		5.901787	

coral_met_dat_site_seabirdcs %>%
   filter(Atoll == "Salomon")%>%
  summarize(range(log_Ninput_kgha)) #-3.0681970				0.5636471	

coral_met_dat_site_seabirdcs %>%
   filter(Atoll == "Peros Banhos")%>%
  summarize(range(log_Ninput_kgha)) #-4.358177				5.232531		

me_coral_G_sb_pp_log_gcb<-
  me_coral_G_sb_pp_log_atollluncenter%>%
  filter(Atoll == "Great Chagos Bank")%>%
  filter(ninput_unscale>=-3.101003 & ninput_unscale<=5.901787)

me_coral_G_sb_pp_log_sal<-
  me_coral_G_sb_pp_log_atollluncenter%>%
  filter(Atoll == "Salomon")%>%
  filter(ninput_unscale>=-3.0681970 & ninput_unscale<=0.5636471)

me_coral_G_sb_pp_log_pb<-
  me_coral_G_sb_pp_log_atollluncenter%>%
  filter(Atoll == "Peros Banhos")%>%
  filter(ninput_unscale>=-4.358177 & ninput_unscale<=5.232531)


#brewer.pal(12, "Set3")
#display.brewer.pal(12, "Set3")
#display.brewer.pal(5, "Reds")
#brewer.pal(5,"Reds")

##create plot, log-labels for seabird n input: 
coral_G_sb_plot<-
coral_met_dat_site_seabirdcs %>%
  mutate(Atoll = fct_relevel(Atoll, c("Great Chagos Bank", "Peros Banhos", "Salomon")))%>%
  ggplot(aes(x = log_Ninput_kgha, y = coral_G_kg_m2_yr)) +
    geom_line(data = me_coral_G_sb_pp_log_gcb, aes(x = ninput_unscale, y = estimate__,  color = Atoll), lwd = 1, lty = 2) + #lty = Atoll,
      geom_line(data = me_coral_G_sb_pp_log_pb, aes(x = ninput_unscale, y = estimate__,  color = Atoll), lwd = 1, lty = 2) + #lty = Atoll,
         geom_line(data = me_coral_G_sb_pp_log_sal, aes(x = ninput_unscale, y = estimate__, color = Atoll), lwd = 1, lty = 2) + #lty = Atoll,
   geom_line(data = me_coral_G_sb_pp_loguncenter, aes(x = ninput_unscale, y = estimate__), lwd = 1.2,  colour = "#FCBBA1") +
        geom_ribbon(data = me_coral_G_sb_pp_loguncenter, aes(x = ninput_unscale, y = estimate__, ymin = lower__, ymax=upper__), 
                    alpha = .2, lwd = 0,  colour = "#FCBBA1", fill = "#FCBBA1")+
       geom_point(aes(shape = Atoll,  fill = Atoll, color = Atoll),size = 2, alpha = .8) + #, size = .8
    ylab(expression(Coral~carbonate~production~(kg~m^-2~yr^-1)))+
    #scale_x_continuous(labels = c(0, 1,  10, 100, 400), breaks = c(log(1), log(10), log(100), log(400)))+
   #scale_x_continuous(labels = c(exp(-2.5), exp(0),exp(2.5),exp(5)), breaks = c(-2.5, 0, 2.5, 5))+
   scale_x_continuous(labels = c(0.1, 1, 10, 100), breaks = c(log(0.1), 0, log(10), log(100)))+
      #fine as is because didn't have to add 1 for log transformation*
    xlab(expression(Seabird~N~input~(kg~ha^-1~yr^-1)))+
  scale_shape_manual(values = c(21, 22, 23))+
   # scale_fill_brewer(palette = "Reds")+
   #   scale_colour_brewer(palette = "Reds")+
  scale_fill_manual(values =c("#FB6A4A", "#DE2D26", "#A50F15"))+
  scale_color_manual(values = c("#FB6A4A", "#DE2D26", "#A50F15"))+
  theme_bw()+
  #guides(lty = "none")+ #fill = "none"
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
             text = element_text(size = 14),
        legend.position = c(0.8, 0.82),
        legend.key.width=unit(0,"cm"),
        legend.background = element_blank(),
         legend.box.background = element_rect()
)

coral_G_sb_plot


#clean up coral plot-----
###make font sizes much smaller:
##create plot, log-labels for seabird n input: 
coral_G_sb_plota4<-
coral_met_dat_site_seabirdcs %>%
  mutate(Atoll = fct_relevel(Atoll, c("Great Chagos Bank", "Peros Banhos", "Salomon")))%>%
  ggplot(aes(x = log_Ninput_kgha, y = coral_G_kg_m2_yr)) +
    geom_line(data = me_coral_G_sb_pp_log_gcb, aes(x = ninput_unscale, y = estimate__,  color = Atoll), lwd = 1, lty = 2) + #lty = Atoll,
      geom_line(data = me_coral_G_sb_pp_log_pb, aes(x = ninput_unscale, y = estimate__,  color = Atoll), lwd = 1, lty = 2) + #lty = Atoll,
         geom_line(data = me_coral_G_sb_pp_log_sal, aes(x = ninput_unscale, y = estimate__, color = Atoll), lwd = 1, lty = 2) + #lty = Atoll,
   geom_line(data = me_coral_G_sb_pp_loguncenter, aes(x = ninput_unscale, y = estimate__), lwd = 1.2,  colour = "#FCBBA1") +
        geom_ribbon(data = me_coral_G_sb_pp_loguncenter, aes(x = ninput_unscale, y = estimate__, ymin = lower__, ymax=upper__), 
                    alpha = .2, lwd = 0,  colour = "#FCBBA1", fill = "#FCBBA1")+
       geom_point(aes(shape = Atoll,  fill = Atoll, color = Atoll),size = 2, alpha = .8) + #, size = .8
    ylab(expression(Coral~carbonate~production~(kg~m^-2~yr^-1)))+
     scale_y_continuous(labels = c(0, 5, 10, 15), breaks = c(0, 5, 10, 15))+
   scale_x_continuous(labels = c(0.1, 1, 10, 100), breaks = c(log(0.1), 0, log(10), log(100)))+
    xlab(expression(Seabird~N~input~(kg~ha^-1~yr^-1)))+
  scale_shape_manual(values = c(21, 22, 23))+
  scale_fill_manual(values =c("#FB6A4A", "#DE2D26", "#A50F15"))+
  scale_color_manual(values = c("#FB6A4A", "#DE2D26", "#A50F15"))+
  theme_bw()+
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
             text = element_text(size = 10),
        legend.position = c(0.79, 0.85),
               legend.key.width=unit(0,"cm"),
        legend.key.spacing.y = unit(-6, "pt"),
         legend.key.spacing.x = unit(0, "pt"),
       legend.text = element_text(size = 6, margin = margin(l=0, b = 0)),
      legend.title = element_text(size = 6, margin = margin(b=-1)),
      legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt"),
        legend.background = element_blank(),
         #legend.box.background = element_rect(),
      legend.box.background = element_blank())


coral_G_sb_plota4


```


#combine and save:
```{r}

###combine and save----
supp_figure_sb_process_a4_vert<-plot_grid(root_length_vs_forest_soiln15_plot_log_axisa4, coral_G_sb_plota4, parrotfish_sed_sb_plota4, align = "hv", labels = "AUTO", label_fontface = "bold", ncol = 1, label_size = 12, hjust = -2.2, vjust = 1.2)


supp_figure_sb_process_a4<-plot_grid(root_length_vs_forest_soiln15_plot_log_axisa4, coral_G_sb_plota4, parrotfish_sed_sb_plota4, labels = "AUTO", label_fontface = "bold", nrow = 1, label_size = 12, align = "hv", hjust = -2)

ggsave(supp_figure_sb_process_a4, filename = "../figures/Supp_Fig_sb_process_A4.jpg", width = 8.2, height = 3.3, units = "in")
#other supplement: width = 8.2, height = 4.1
#OG: width = 8.2, height = 3




```

